### ISSUE TITLE
question about

### ISSUE THREAD

**Issue by Phil-Lin** [baoshengyu/H3R#2]
你好，请问编码后，训练的监督信息就是真实点周围的四个整数点的概率？？

**Comment by baoshengyu** [comment]
"we randomly assign the ground truth activation point to one of the alternative activation points around the ground truth activation point, and the activation probability is determined by the fractional part of the ground truth activation point". 

Please also find details in Section 4.4.

**Comment by Phil-Lin** [comment]
thanks for your response. That‘s my question that,  if you assign the ground truth activation point to one of the alternative activation points around the ground truth activation point, how to decode the the fractional part of the ground truth numerical coordinate. Isn't the fractional part of the ground truth numerical coordinate reconstructed by the activation probabilities of all activation points in (17)?

**Comment by baoshengyu** [comment]
"the activation probability depends on the fractional part of the ground truth numerical coordinates".  

The ground truth activation point will be randomly assigned to one of the alternative activation points in each mini batch according to the fractional part of the ground truth numerical coordinates (i.e., the activation probability).  

Please also find the definition of the randomized rounding operation. 

Hope this helps.

**Comment by Phil-Lin** [comment]
So , during training phase, one of the alternative activation points (randomized rounding) and its probability is as supervision information. Do I understand correctly??

**Comment by baoshengyu** [comment]
The activation probability is not explicitly used as the supervision during training. Apart from the encode and decode opearations, the proposed method is similar to typical heatmap-based methods for semantic landmark localization.
