### ISSUE TITLE
Heatmap block

### ISSUE THREAD

**Issue by datvtn** [baoshengyu/H3R#4]
Hi author, 
In my opinion, the heatmap has the form (1, 106, 64, 64) but when I get the output of the heatmap block it has the form (1, 2, 106, 64, 64), can you explain it? Can I combine and find all 106 heatmap combinations to 1?

**Comment by baoshengyu** [comment]
The first channel indiates the background.

**Comment by pha-nguyen** [comment]
@baoshengyu could you please explain to me how the first channel is computed (or the loss function to train it), what is the meaning of the first channel in terms of guiding the network?
